spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mariadb://localhost:53306/home-organizer
    username: root
    password: mariadb
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update


server:
  port: 5537
  forward-headers-strategy: native

logging:
  level:
    root: warn
    com.grossmann.apps.homeorganizer: info
